version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Light80s!
      MYSQL_DATABASE: CHEESESHOP
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Light80s!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4001:3306"